export const QUERY_KEY = {
  CARDS: 'CARDS',
  LEARN_CARD: 'LEARN_CARD',
  CURRENT_LEARN_SESSION: 'CURRENT_LEARN_SESSION',
  MODULES: 'MODULES',
  LEARN_SESSIONS: 'LEARN_SESSIONS',
  FOLDERS: 'FOLDERS',
}
